<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Clio.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModel\Content\TaskContent.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ObjectModel" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\AspClientServerPlatform.Mk1\Core\Core.Lib\Core.Lib.csproj" />
    <ProjectReference Include="..\..\..\AspClientServerPlatform.Mk1\Core\Core8\Core8.csproj" />
    <ProjectReference Include="..\ProjectManager.DTO\ProjectManager.DTO.csproj" />
  </ItemGroup>

</Project>
