<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Clio.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="sql\migration\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\AspClientServerPlatform.Mk1\Core\Core.Lib\Core.Lib.csproj" />
  </ItemGroup>

</Project>
